### ISSUE TITLE
No Examples here - http://engine.qiciengine.com/demo demoscripts minified.

### ISSUE THREAD

**Issue by soundyogi** [qiciengine/qiciengine-examples#1]
Title says it.

Why are all the demo scripts minified? Not very helpful :)

**Comment by linyiwei** [comment]
When a demo is published, it's run on the minified script, but all the source codes are in the "Scripts" directory of each example project, such as https://github.com/qiciengine/qiciengine-examples/tree/master/projects/Project/JumpingBrick/Scripts
