### ISSUE TITLE
Dota Demo Plays Sound While tab is hidden.

### ISSUE THREAD

**Issue by Morabaraba** [qiciengine/qiciengine-examples#2]
Should the game not get paused?

Can I maybe implement it later the week, and any guide on how to, eg, example project, manual, api, url?

You guys reality made a huge collection of resources available, so I'm struggling to add the bits and pieces together, but I am enjoying it.

Thanks,

**Comment by armoonqici** [comment]
1. 'RunInBackground' is enable default. (see menu: Project Settings)
2. Documentation here: https://github.com/qiciengine/qiciengine-documentation. You can start from Manual.

**Comment by Morabaraba** [comment]
Missed that, thanks.

But after disabling "Run In Background" the `qc.Sound` object "background music" still played music. I tried this with `Project/sources`.

I would expect no sound to play when  "Run In Background" is disabled? 
Or might it be a browser issue?

Win 10, Version 48.0.2564.97 m

**Comment by huhudage** [comment]
In my browser, the "background music" was not played after disabling "Run In Background", maybe you forgot to click the 'Apply' button after disabling the option in Project Settings panel?

**Comment by Morabaraba** [comment]
@huhudage thanks
